# Documentation: http://docs.travis-ci.com/user/languages/julia/
language: julia
os:
  - linux
  - osx
julia:
  - 0.7
  - 1.0
  - nightly
matrix:
  allow_failures:
    - julia: nightly
addons:
    apt_packages:
        - gfortran
notifications:
  email: false
git:
  depth: 99999999

# before_script: # install dependent unregistered packages
#   - if [[ -a .git/shallow ]]; then git fetch --unshallow; fi
#   - julia -e 'using Pkg; Pkg.add([PackageSpec(url="https://github.com/OpenMendel/VarianceComponentModels.jl.git", rev="juliav0.7"), PackageSpec(url="https://github.com/OpenMendel/VarianceComponentModels.jl.git", rev="master")]);'
after_script:  # TODO: change to after_success once https://github.com/JuliaLang/julia/issues/28306 is fixed
  # push coverage results to Codecov and Coveralls
  - julia -e 'using Pkg, VarianceComponentModels; cd(joinpath(dirname(pathof(VarianceComponentModels)), "..")); Pkg.add("Coverage"); using Coverage; Codecov.submit(process_folder()); Coveralls.submit(process_folder())'

jobs:
  include:
    - stage: "Documentation"
      julia: 1.0
      os: osx
      script:
        - julia -e 'using Pkg; Pkg.add("Documenter")'
        - julia -e 'using VarianceComponentModels; include(joinpath(dirname(pathof(VarianceComponentModels)), "..", "docs", "make.jl"))'
      after_script: skip
      after_success: skip